export const videoGuru = [
  {
    id: 1001,
    title: 'Кундалини-самадхи и сахадж-самадхи, в чём разница?',
    category: "",
    url: "https://vk.com/video_ext.php?oid=40782986&id=456241012&hd=2",
    sourse: "vk",
  },
  {
    id: 1002,
    title: 'О Нирвикальпа Самадхи. Из сатсанга Шри Гуру Свами Вишнудевананда Гири Махараджа',
    category: "",
    url: "https://vk.com/video_ext.php?oid=40782986&id=456241118&hd=2",
    sourse: "vk",
  },
  {
    id: 1003,
    title: 'Ловушка пустоты, состояние пралаякала',
    category: "",
    url: "https://vk.com/video_ext.php?oid=40782986&id=456241180&hd=2",
    sourse: "vk",
  },
  {
    id: 1004,
    title: 'Оджас, теджас, прана. ',
    category: "",
    url: "https://vk.com/video_ext.php?oid=40782986&id=456241286&hd=2",
    sourse: "vk",
  },
  {
    id: 1005,
    title: 'Свет матери и сына.',
    category: "",
    url: "https://vk.com/video_ext.php?oid=40782986&id=456241089&hd=2",
    sourse: "vk",
  },
  {
    id: 1006,
    title: 'Бог - не чужой.',
    category: "",
    url: "https://vk.com/video_ext.php?oid=40782986&id=456241088&hd=2",
    sourse: "vk",
  },
  {
    id: 1007,
    title: 'Смысл обретения Символа Веры и Прибежища для души 🕉',
    category: "",
    url: "https://vk.com/video_ext.php?oid=40782986&id=456240899&hd=2",
    sourse: "vk",
  },
  {
    id: 1008,
    title: 'Как отличить игры ума от просветления',
    category: "",
    url: "https://vk.com/video_ext.php?oid=40782986&id=456240701&hd=2",
    sourse: "vk",
  },
  {
    id: 100,
    title: '',
    category: "",
    url: "",
    sourse: "vk",
  },
  {
    id: 100,
    title: '',
    category: "",
    url: "",
    sourse: "vk",
  },
  {
    id: 100,
    title: '',
    category: "",
    url: "",
    sourse: "vk",
  },
  {
    id: 100,
    title: '',
    category: "",
    url: "",
    sourse: "vk",
  },
  {
    id: 100,
    title: '',
    category: "",
    url: "",
    sourse: "vk",
  },
  {
    id: 100,
    title: '',
    category: "",
    url: "",
    sourse: "vk",
  },
  {
    id: 100,
    title: '',
    category: "",
    url: "",
    sourse: "vk",
  },
  {
    id: 100,
    title: '',
    category: "",
    url: "",
    sourse: "vk",
  },
]