export const videoSanyasi = [
  {
    id: 4025,
    title: 'Йогин проживший 287 лет',
    category: "",
    url: "https://dzen.ru/embed/v_X8NIpz2wTU?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4024,
    title: 'Сумеречный язык тантры',
    category: "",
    url: "https://dzen.ru/embed/vcgqb4gbblXk?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4023,
    title: 'Хатха и кундалини-йога, вопросы-ответы',
    category: "",
    url: "https://dzen.ru/embed/vMapSOCCgZA4?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4022,
    title: 'Шат-чакра-нирупана',
    category: "",
    url: "https://dzen.ru/embed/vnd-BNplVYTU?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4021,
    title: 'Красная и белая капли',
    category: "",
    url: "https://dzen.ru/embed/vaXR15pp1ASE?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4020,
    title: 'Собрать ветра в чакрах',
    category: "",
    url: "https://dzen.ru/embed/vpVIJ1Mgg01Q?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4019,
    title: 'Сила чакр против чужих мыслей',
    category: "",
    url: "https://dzen.ru/embed/v_-Ulb5Cu42o?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4018,
    title: 'Сколько чакрам уделять внимания',
    category: "",
    url: "https://dzen.ru/embed/vbEDOPORMZmY?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4017,
    title: 'Подробно о пратьяхаре',
    category: "",
    url: "https://dzen.ru/embed/v2m7HD9XRAlA?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4016,
    title: 'Подготовка тела к длительным медитациям',
    category: "",
    url: "https://dzen.ru/embed/vz-Xjvp31j1A?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4015,
    title: 'Подробно о типах и темпах ритритов',
    category: "",
    url: "https://dzen.ru/embed/vc7rcjcixXS0?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4014,
    title: 'Ориентировочная программа трехлетнего ритрита',
    category: "",
    url: "https://dzen.ru/embed/vIk-weAF7byU?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4013,
    title: 'Что делать с начальными препятствиями в ритрите',
    category: "",
    url: "https://dzen.ru/embed/v5Ss6vEpirkY?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4012,
    title: 'Что ожидает затворника в ритрите',
    category: "",
    url: "https://dzen.ru/embed/vm6DnWCCodU8?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4011,
    title: 'Подробно о самадхи',
    category: "",
    url: "https://dzen.ru/embed/vzaqm2G_WTX0?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4010,
    title: 'Йога-пада и джняна-пада',
    category: "",
    url: "https://dzen.ru/embed/vF6hUMM7FKSw?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4009,
    title: 'Чарья-пада и крийя-пада',
    category: "",
    url: "https://dzen.ru/embed/v8avgMw28hh4?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4008,
    title: 'Стартовая площадка медитации покоя',
    category: "",
    url: "https://dzen.ru/embed/vJtXPDzXIUVQ?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4007,
    title: 'Подробно о ключах медитации',
    category: "",
    url: "https://dzen.ru/embed/veMD0ODTsghE?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4006,
    title: 'Девять способов пробуждения кундалини шакти',
    category: "",
    url: "https://dzen.ru/embed/vVlJ6dR9XhEc?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4005,
    title: 'Подробно об атма-вичаре',
    category: "",
    url: "https://dzen.ru/embed/v8s45WUum1FQ?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4004,
    title: 'Подробно о медитации анапанасати',
    category: "",
    url: "https://dzen.ru/embed/vD09kzlwVcn8?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4003,
    title: 'Подготовка к медитации чандали',
    category: "",
    url: "https://dzen.ru/embed/vBFrdguoN6j4?from_block=partner&from=zen&mute=0&autoplay=0&tv=0",
    sourse: "dzen",
  },
  {
    id: 4002,
    title: 'Что такое чистое видение',
    category: "",
    url: "https://vk.com/video_ext.php?oid=40782986&id=456241205&hd=2",
    sourse: "vk",
  },
  {
    id: 4001,
    title: 'Этапы развития концентрации внимания',
    category: "",
    url: "https://vk.com/video_ext.php?oid=40782986&id=456241129&hd=2",
    sourse: "vk",
  },
]
